#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 13

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_EQ = 2,
  anon_sym_PIPE = 3,
  sym__ws = 4,
  sym__line_end = 5,
  sym__indent = 6,
  sym__continue = 7,
  sym__dedent = 8,
  sym_identifier = 9,
  sym_text_start = 10,
  sym_text_fragment = 11,
  sym_string = 12,
  sym_comment = 13,
  sym_error = 14,
  sym_source_file = 15,
  sym_object = 16,
  sym_section = 17,
  sym_body = 18,
  sym_struct_row = 19,
  sym_table_row = 20,
  sym_text = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_body_repeat1 = 23,
  aux_sym_table_row_repeat1 = 24,
  aux_sym_text_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE] = "|",
  [sym__ws] = "_ws",
  [sym__line_end] = "_line_end",
  [sym__indent] = "_indent",
  [sym__continue] = "_continue",
  [sym__dedent] = "_dedent",
  [sym_identifier] = "identifier",
  [sym_text_start] = "text_fragment",
  [sym_text_fragment] = "text_fragment",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym_error] = "error",
  [sym_source_file] = "source_file",
  [sym_object] = "object",
  [sym_section] = "section",
  [sym_body] = "body",
  [sym_struct_row] = "struct_row",
  [sym_table_row] = "table_row",
  [sym_text] = "text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_table_row_repeat1] = "table_row_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym__ws] = sym__ws,
  [sym__line_end] = sym__line_end,
  [sym__indent] = sym__indent,
  [sym__continue] = sym__continue,
  [sym__dedent] = sym__dedent,
  [sym_identifier] = sym_identifier,
  [sym_text_start] = sym_text_fragment,
  [sym_text_fragment] = sym_text_fragment,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym_error] = sym_error,
  [sym_source_file] = sym_source_file,
  [sym_object] = sym_object,
  [sym_section] = sym_section,
  [sym_body] = sym_body,
  [sym_struct_row] = sym_struct_row,
  [sym_table_row] = sym_table_row,
  [sym_text] = sym_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_table_row_repeat1] = aux_sym_table_row_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym__line_end] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__continue] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_text_start] = {
    .visible = true,
    .named = true,
  },
  [sym_text_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_error] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_row] = {
    .visible = true,
    .named = true,
  },
  [sym_table_row] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_row_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_base = 1,
  field_body = 2,
  field_key = 3,
  field_name = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_base] = "base",
  [field_body] = "body",
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 2},
  [7] = {.index = 12, .length = 1},
  [8] = {.index = 13, .length = 3},
  [9] = {.index = 16, .length = 2},
  [10] = {.index = 18, .length = 2},
  [11] = {.index = 20, .length = 2},
  [12] = {.index = 22, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_base, 0},
    {field_name, 2},
  [2] =
    {field_base, 0},
    {field_body, 4},
    {field_name, 2},
  [5] =
    {field_base, 0},
    {field_name, 3},
  [7] =
    {field_base, 0},
    {field_body, 5},
    {field_name, 3},
  [10] =
    {field_base, 0},
    {field_name, 4},
  [12] =
    {field_name, 0},
  [13] =
    {field_base, 0},
    {field_body, 6},
    {field_name, 4},
  [16] =
    {field_body, 2},
    {field_name, 0},
  [18] =
    {field_key, 0},
    {field_value, 2},
  [20] =
    {field_key, 0},
    {field_value, 3},
  [22] =
    {field_key, 0},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [4] = {
    [0] = sym_text_fragment,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 15,
  [21] = 21,
  [22] = 17,
  [23] = 23,
  [24] = 16,
  [25] = 18,
  [26] = 14,
  [27] = 27,
  [28] = 11,
  [29] = 8,
  [30] = 10,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 39,
  [41] = 32,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 38,
  [51] = 51,
  [52] = 52,
  [53] = 34,
  [54] = 54,
  [55] = 33,
  [56] = 35,
  [57] = 36,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 52,
  [62] = 43,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 47,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 64,
  [75] = 68,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 72,
  [80] = 80,
  [81] = 76,
  [82] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == '=') ADVANCE(3);
      if (lookahead == '|') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 5},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0, .external_lex_state = 5},
  [14] = {.lex_state = 0, .external_lex_state = 6},
  [15] = {.lex_state = 0, .external_lex_state = 6},
  [16] = {.lex_state = 0, .external_lex_state = 6},
  [17] = {.lex_state = 0, .external_lex_state = 6},
  [18] = {.lex_state = 0, .external_lex_state = 6},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 7},
  [21] = {.lex_state = 0, .external_lex_state = 8},
  [22] = {.lex_state = 0, .external_lex_state = 7},
  [23] = {.lex_state = 0, .external_lex_state = 5},
  [24] = {.lex_state = 0, .external_lex_state = 7},
  [25] = {.lex_state = 0, .external_lex_state = 7},
  [26] = {.lex_state = 0, .external_lex_state = 7},
  [27] = {.lex_state = 0, .external_lex_state = 5},
  [28] = {.lex_state = 0, .external_lex_state = 8},
  [29] = {.lex_state = 0, .external_lex_state = 8},
  [30] = {.lex_state = 0, .external_lex_state = 8},
  [31] = {.lex_state = 0, .external_lex_state = 9},
  [32] = {.lex_state = 0, .external_lex_state = 10},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 10},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 10},
  [40] = {.lex_state = 0, .external_lex_state = 10},
  [41] = {.lex_state = 0, .external_lex_state = 10},
  [42] = {.lex_state = 0, .external_lex_state = 11},
  [43] = {.lex_state = 0, .external_lex_state = 12},
  [44] = {.lex_state = 0, .external_lex_state = 10},
  [45] = {.lex_state = 0, .external_lex_state = 10},
  [46] = {.lex_state = 0, .external_lex_state = 10},
  [47] = {.lex_state = 0, .external_lex_state = 11},
  [48] = {.lex_state = 0, .external_lex_state = 10},
  [49] = {.lex_state = 0, .external_lex_state = 10},
  [50] = {.lex_state = 0, .external_lex_state = 10},
  [51] = {.lex_state = 0, .external_lex_state = 11},
  [52] = {.lex_state = 0, .external_lex_state = 12},
  [53] = {.lex_state = 0, .external_lex_state = 10},
  [54] = {.lex_state = 0, .external_lex_state = 11},
  [55] = {.lex_state = 0, .external_lex_state = 10},
  [56] = {.lex_state = 0, .external_lex_state = 10},
  [57] = {.lex_state = 0, .external_lex_state = 10},
  [58] = {.lex_state = 0, .external_lex_state = 11},
  [59] = {.lex_state = 0, .external_lex_state = 11},
  [60] = {.lex_state = 0, .external_lex_state = 10},
  [61] = {.lex_state = 0, .external_lex_state = 12},
  [62] = {.lex_state = 0, .external_lex_state = 12},
  [63] = {.lex_state = 0, .external_lex_state = 11},
  [64] = {.lex_state = 0, .external_lex_state = 9},
  [65] = {.lex_state = 0, .external_lex_state = 11},
  [66] = {.lex_state = 0, .external_lex_state = 11},
  [67] = {.lex_state = 0, .external_lex_state = 11},
  [68] = {.lex_state = 0, .external_lex_state = 9},
  [69] = {.lex_state = 0, .external_lex_state = 9},
  [70] = {.lex_state = 0, .external_lex_state = 9},
  [71] = {.lex_state = 0, .external_lex_state = 9},
  [72] = {.lex_state = 0, .external_lex_state = 12},
  [73] = {.lex_state = 0, .external_lex_state = 9},
  [74] = {.lex_state = 0, .external_lex_state = 9},
  [75] = {.lex_state = 0, .external_lex_state = 9},
  [76] = {.lex_state = 0, .external_lex_state = 12},
  [77] = {.lex_state = 0, .external_lex_state = 9},
  [78] = {.lex_state = 0, .external_lex_state = 11},
  [79] = {.lex_state = 0, .external_lex_state = 12},
  [80] = {.lex_state = 0, .external_lex_state = 9},
  [81] = {.lex_state = 0, .external_lex_state = 12},
  [82] = {.lex_state = 0, .external_lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [sym__line_end] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__continue] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_text_start] = ACTIONS(1),
    [sym_text_fragment] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_error] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(78),
    [sym_object] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__line_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PIPE,
    ACTIONS(13), 1,
      sym__line_end,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_text_start,
    ACTIONS(19), 1,
      sym_string,
    STATE(59), 1,
      aux_sym_table_row_repeat1,
    STATE(80), 1,
      sym_text,
    STATE(60), 4,
      sym_object,
      sym_section,
      sym_struct_row,
      sym_table_row,
  [31] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PIPE,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_text_start,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym__line_end,
    STATE(59), 1,
      aux_sym_table_row_repeat1,
    STATE(80), 1,
      sym_text,
    STATE(39), 4,
      sym_object,
      sym_section,
      sym_struct_row,
      sym_table_row,
  [62] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PIPE,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_text_start,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(23), 1,
      sym__line_end,
    STATE(59), 1,
      aux_sym_table_row_repeat1,
    STATE(80), 1,
      sym_text,
    STATE(40), 4,
      sym_object,
      sym_section,
      sym_struct_row,
      sym_table_row,
  [93] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym__ws,
    ACTIONS(27), 1,
      sym__line_end,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_text_start,
    ACTIONS(33), 1,
      sym_string,
    STATE(51), 1,
      sym_text,
  [115] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      sym__line_end,
    STATE(7), 2,
      sym_object,
      aux_sym_source_file_repeat1,
  [132] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      sym__line_end,
    ACTIONS(44), 1,
      sym_identifier,
    STATE(7), 2,
      sym_object,
      aux_sym_source_file_repeat1,
  [149] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym__indent,
    STATE(34), 1,
      sym_body,
    ACTIONS(47), 3,
      sym__line_end,
      sym_identifier,
      ts_builtin_sym_end,
  [164] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      sym__ws,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_text_start,
    ACTIONS(33), 1,
      sym_string,
    STATE(51), 1,
      sym_text,
  [183] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym__indent,
    STATE(35), 1,
      sym_body,
    ACTIONS(51), 3,
      sym__line_end,
      sym_identifier,
      ts_builtin_sym_end,
  [198] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym__indent,
    STATE(38), 1,
      sym_body,
    ACTIONS(53), 3,
      sym__line_end,
      sym_identifier,
      ts_builtin_sym_end,
  [213] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_text_start,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(55), 1,
      sym__ws,
    ACTIONS(57), 1,
      sym_identifier,
    STATE(71), 1,
      sym_text,
  [232] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_text_start,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym__ws,
    STATE(77), 1,
      sym_text,
  [251] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(16), 1,
      aux_sym_text_repeat1,
    ACTIONS(61), 2,
      anon_sym_PIPE,
      sym__ws,
    ACTIONS(63), 2,
      sym_text_fragment,
      sym_string,
  [266] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym_text_repeat1,
    ACTIONS(65), 2,
      anon_sym_PIPE,
      sym__ws,
    ACTIONS(67), 2,
      sym_text_fragment,
      sym_string,
  [281] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_text_repeat1,
    ACTIONS(69), 2,
      anon_sym_PIPE,
      sym__ws,
    ACTIONS(71), 2,
      sym_text_fragment,
      sym_string,
  [296] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_text_repeat1,
    ACTIONS(71), 2,
      sym_text_fragment,
      sym_string,
    ACTIONS(73), 2,
      anon_sym_PIPE,
      sym__ws,
  [311] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_text_repeat1,
    ACTIONS(75), 2,
      anon_sym_PIPE,
      sym__ws,
    ACTIONS(77), 2,
      sym_text_fragment,
      sym_string,
  [326] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_text_start,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(57), 1,
      sym_identifier,
    STATE(77), 1,
      sym_text,
  [342] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym__line_end,
    STATE(22), 1,
      aux_sym_text_repeat1,
    ACTIONS(80), 2,
      sym_text_fragment,
      sym_string,
  [356] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym__indent,
    STATE(44), 1,
      sym_body,
    ACTIONS(84), 2,
      sym__continue,
      sym__dedent,
  [370] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym__line_end,
    STATE(25), 1,
      aux_sym_text_repeat1,
    ACTIONS(86), 2,
      sym_text_fragment,
      sym_string,
  [384] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_text_start,
    ACTIONS(33), 1,
      sym_string,
    STATE(42), 1,
      sym_text,
  [400] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym__line_end,
    STATE(25), 1,
      aux_sym_text_repeat1,
    ACTIONS(86), 2,
      sym_text_fragment,
      sym_string,
  [414] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      sym__line_end,
    STATE(25), 1,
      aux_sym_text_repeat1,
    ACTIONS(88), 2,
      sym_text_fragment,
      sym_string,
  [428] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym__line_end,
    STATE(24), 1,
      aux_sym_text_repeat1,
    ACTIONS(91), 2,
      sym_text_fragment,
      sym_string,
  [442] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_text_start,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(57), 1,
      sym_identifier,
    STATE(70), 1,
      sym_text,
  [458] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym__indent,
    STATE(50), 1,
      sym_body,
    ACTIONS(53), 2,
      sym__continue,
      sym__dedent,
  [472] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym__indent,
    STATE(53), 1,
      sym_body,
    ACTIONS(47), 2,
      sym__continue,
      sym__dedent,
  [486] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym__indent,
    STATE(56), 1,
      sym_body,
    ACTIONS(51), 2,
      sym__continue,
      sym__dedent,
  [500] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym__line_end,
    ACTIONS(93), 1,
      anon_sym_COLON,
    ACTIONS(95), 1,
      anon_sym_EQ,
    ACTIONS(97), 1,
      sym__ws,
  [516] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym__continue,
    ACTIONS(101), 1,
      sym__dedent,
    STATE(37), 1,
      aux_sym_body_repeat1,
  [529] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 3,
      sym__line_end,
      sym_identifier,
      ts_builtin_sym_end,
  [538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 3,
      sym__line_end,
      sym_identifier,
      ts_builtin_sym_end,
  [547] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 3,
      sym__line_end,
      sym_identifier,
      ts_builtin_sym_end,
  [556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 3,
      sym__line_end,
      sym_identifier,
      ts_builtin_sym_end,
  [565] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym__continue,
    ACTIONS(114), 1,
      sym__dedent,
    STATE(37), 1,
      aux_sym_body_repeat1,
  [578] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 3,
      sym__line_end,
      sym_identifier,
      ts_builtin_sym_end,
  [587] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym__continue,
    ACTIONS(118), 1,
      sym__dedent,
    STATE(32), 1,
      aux_sym_body_repeat1,
  [600] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym__continue,
    ACTIONS(120), 1,
      sym__dedent,
    STATE(41), 1,
      aux_sym_body_repeat1,
  [613] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym__continue,
    ACTIONS(122), 1,
      sym__dedent,
    STATE(37), 1,
      aux_sym_body_repeat1,
  [626] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PIPE,
    ACTIONS(126), 1,
      sym__ws,
  [636] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym__ws,
    ACTIONS(130), 1,
      sym_identifier,
  [646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      sym__continue,
      sym__dedent,
  [654] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      sym__continue,
      sym__dedent,
  [662] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 2,
      sym__continue,
      sym__dedent,
  [670] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 2,
      anon_sym_PIPE,
      sym__ws,
  [678] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      sym__continue,
      sym__dedent,
  [686] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 2,
      sym__continue,
      sym__dedent,
  [694] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 2,
      sym__continue,
      sym__dedent,
  [702] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(144), 1,
      sym__ws,
  [712] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym__ws,
    ACTIONS(148), 1,
      sym_identifier,
  [722] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      sym__continue,
      sym__dedent,
  [730] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_COLON,
    ACTIONS(152), 1,
      sym__ws,
  [740] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      sym__continue,
      sym__dedent,
  [748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      sym__continue,
      sym__dedent,
  [756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      sym__continue,
      sym__dedent,
  [764] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    STATE(58), 1,
      aux_sym_table_row_repeat1,
  [774] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_PIPE,
    STATE(58), 1,
      aux_sym_table_row_repeat1,
  [784] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 2,
      sym__continue,
      sym__dedent,
  [792] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym__ws,
    ACTIONS(161), 1,
      sym_identifier,
  [802] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym__ws,
    ACTIONS(165), 1,
      sym_identifier,
  [812] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_COLON,
    ACTIONS(169), 1,
      anon_sym_EQ,
  [822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym__line_end,
  [829] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_PIPE,
  [836] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_PIPE,
  [843] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COLON,
  [850] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym__line_end,
  [857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym__line_end,
  [864] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym__line_end,
  [871] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym__line_end,
  [878] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_identifier,
  [885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym__line_end,
  [892] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__line_end,
  [899] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym__line_end,
  [906] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
  [913] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym__line_end,
  [920] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
  [927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_identifier,
  [934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym__line_end,
  [941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
  [948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      sym__line_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 115,
  [SMALL_STATE(7)] = 132,
  [SMALL_STATE(8)] = 149,
  [SMALL_STATE(9)] = 164,
  [SMALL_STATE(10)] = 183,
  [SMALL_STATE(11)] = 198,
  [SMALL_STATE(12)] = 213,
  [SMALL_STATE(13)] = 232,
  [SMALL_STATE(14)] = 251,
  [SMALL_STATE(15)] = 266,
  [SMALL_STATE(16)] = 281,
  [SMALL_STATE(17)] = 296,
  [SMALL_STATE(18)] = 311,
  [SMALL_STATE(19)] = 326,
  [SMALL_STATE(20)] = 342,
  [SMALL_STATE(21)] = 356,
  [SMALL_STATE(22)] = 370,
  [SMALL_STATE(23)] = 384,
  [SMALL_STATE(24)] = 400,
  [SMALL_STATE(25)] = 414,
  [SMALL_STATE(26)] = 428,
  [SMALL_STATE(27)] = 442,
  [SMALL_STATE(28)] = 458,
  [SMALL_STATE(29)] = 472,
  [SMALL_STATE(30)] = 486,
  [SMALL_STATE(31)] = 500,
  [SMALL_STATE(32)] = 516,
  [SMALL_STATE(33)] = 529,
  [SMALL_STATE(34)] = 538,
  [SMALL_STATE(35)] = 547,
  [SMALL_STATE(36)] = 556,
  [SMALL_STATE(37)] = 565,
  [SMALL_STATE(38)] = 578,
  [SMALL_STATE(39)] = 587,
  [SMALL_STATE(40)] = 600,
  [SMALL_STATE(41)] = 613,
  [SMALL_STATE(42)] = 626,
  [SMALL_STATE(43)] = 636,
  [SMALL_STATE(44)] = 646,
  [SMALL_STATE(45)] = 654,
  [SMALL_STATE(46)] = 662,
  [SMALL_STATE(47)] = 670,
  [SMALL_STATE(48)] = 678,
  [SMALL_STATE(49)] = 686,
  [SMALL_STATE(50)] = 694,
  [SMALL_STATE(51)] = 702,
  [SMALL_STATE(52)] = 712,
  [SMALL_STATE(53)] = 722,
  [SMALL_STATE(54)] = 730,
  [SMALL_STATE(55)] = 740,
  [SMALL_STATE(56)] = 748,
  [SMALL_STATE(57)] = 756,
  [SMALL_STATE(58)] = 764,
  [SMALL_STATE(59)] = 774,
  [SMALL_STATE(60)] = 784,
  [SMALL_STATE(61)] = 792,
  [SMALL_STATE(62)] = 802,
  [SMALL_STATE(63)] = 812,
  [SMALL_STATE(64)] = 822,
  [SMALL_STATE(65)] = 829,
  [SMALL_STATE(66)] = 836,
  [SMALL_STATE(67)] = 843,
  [SMALL_STATE(68)] = 850,
  [SMALL_STATE(69)] = 857,
  [SMALL_STATE(70)] = 864,
  [SMALL_STATE(71)] = 871,
  [SMALL_STATE(72)] = 878,
  [SMALL_STATE(73)] = 885,
  [SMALL_STATE(74)] = 892,
  [SMALL_STATE(75)] = 899,
  [SMALL_STATE(76)] = 906,
  [SMALL_STATE(77)] = 913,
  [SMALL_STATE(78)] = 920,
  [SMALL_STATE(79)] = 927,
  [SMALL_STATE(80)] = 934,
  [SMALL_STATE(81)] = 941,
  [SMALL_STATE(82)] = 948,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5, 0, 3),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 6, 0, 6),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 2, 0, 4),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 7),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 6, 0, 5),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 7, 0, 8),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5, 0, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_row_repeat1, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 9),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_row, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_row, 4, 0, 10),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_row, 5, 0, 11),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_row, 6, 0, 12),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_row_repeat1, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [193] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__line_end = 0,
  ts_external_token__indent = 1,
  ts_external_token__continue = 2,
  ts_external_token__dedent = 3,
  ts_external_token_identifier = 4,
  ts_external_token_text_start = 5,
  ts_external_token_text_fragment = 6,
  ts_external_token_string = 7,
  ts_external_token_comment = 8,
  ts_external_token_error = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__line_end] = sym__line_end,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__continue] = sym__continue,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token_identifier] = sym_identifier,
  [ts_external_token_text_start] = sym_text_start,
  [ts_external_token_text_fragment] = sym_text_fragment,
  [ts_external_token_string] = sym_string,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_error] = sym_error,
};

static const bool ts_external_scanner_states[13][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__line_end] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__continue] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_identifier] = true,
    [ts_external_token_text_start] = true,
    [ts_external_token_text_fragment] = true,
    [ts_external_token_string] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_error] = true,
  },
  [2] = {
    [ts_external_token__line_end] = true,
    [ts_external_token_identifier] = true,
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__line_end] = true,
    [ts_external_token_identifier] = true,
    [ts_external_token_text_start] = true,
    [ts_external_token_string] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token__line_end] = true,
    [ts_external_token__indent] = true,
    [ts_external_token_identifier] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_identifier] = true,
    [ts_external_token_text_start] = true,
    [ts_external_token_string] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_text_fragment] = true,
    [ts_external_token_string] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token__line_end] = true,
    [ts_external_token_text_fragment] = true,
    [ts_external_token_string] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token__indent] = true,
    [ts_external_token__continue] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token__line_end] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token__continue] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_comment] = true,
  },
  [11] = {
    [ts_external_token_comment] = true,
  },
  [12] = {
    [ts_external_token_identifier] = true,
    [ts_external_token_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_gml_external_scanner_create(void);
void tree_sitter_gml_external_scanner_destroy(void *);
bool tree_sitter_gml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_gml_external_scanner_serialize(void *, char *);
void tree_sitter_gml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_gml_external_scanner_create,
      tree_sitter_gml_external_scanner_destroy,
      tree_sitter_gml_external_scanner_scan,
      tree_sitter_gml_external_scanner_serialize,
      tree_sitter_gml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
